title: "FatalError | System Logs of sysnomad"
author: sysnomad
description: Essays on stories, film, and the human glitch.
baseurl: "" # leave empty
url: "https://fatalerror-lol.github.io/" # Change this to your actual GitHub URL


# This ensures your footnotes work correctly
markdown: kramdown
kramdown:
  footnote_nr: 1
  
# Exclude things you don't want the public to see
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor